### ISSUE TITLE
Explore pycuda as an option to write custom cuda code with cudf

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/rapids-examples#10]
### Explore pycuda as an option to write custom cuda code  with cudf 
With a recent [PR](https://github.com/inducer/pycuda/pull/270) pycuda got `__cuda_array_interface__ ` allowing interoperability with numba,cupy etc.  Pycuda in theory allows us access to the whole [cuda driver API](https://documen.tician.de/pycuda/#welcome-to-pycuda-s-documentation). It might be worth exploring how we can use it with cudf. 

Having examples that do operations like https://github.com/rapidsai/rapids-examples/tree/main/shareable-dataframes but with Pycuda might make access to CUDA kernels easier without too much glue code. 

An example to create will be something on the lines @jdye64  did but with `pycuda`

Helpful links: 
1. https://documen.tician.de/pycuda/tutorial.html#executing-a-kernel
2. https://documen.tician.de/pycuda/tutorial.html?highlight=numba#interoperability-with-other-libraries-using-the-cuda-array-interface

CC: @beckernick , @randerzander , @jdye64 .

**Comment by randerzander** [comment]
Would the CUDA code strings be JIT compiled with pycuda?

If so, is there a cache so that you only pay the compilation tax the first time you run?

**Comment by VibhuJawa** [comment]
> Would the CUDA code strings be JIT compiled with pycuda?

Yup, they would be JIT compiled,  cached as well as loaded to the device when we  call `pycuda.compiler.SourceModule('''Cuda code striing''')` so it should be a one time cost.
