### ISSUE TITLE
string_udf example cleanup

### ISSUE THREAD

**Issue by randerzander** [rapidsai/rapids-examples#7]
Let's make the string_udf example simpler with Python bindings that work with cudf Python. Something like:

```
import cudf
df = cudf.DataFrame({'id': [0, 1, 2], 'val': ['abc', 'def', 'ghi']}

df['result'] = cpp_string_udf(df['val'])
```

instead of a CLI binary

**Comment by jdye64** [comment]
This is now complete as part of PR https://github.com/rapidsai/rapids-examples/pull/19
